export const featureList = [
  "Auto-replies",
  "Personalized greetings",
  "Queries per month",
  "Storage space",
  "Artwork recommendations",
  "Daily fortune draw game",
  "Transaction and sales tracking",
  "Fraud protection",
  "Customizable chat responses",
  "AI-generated buyer recommendations",
  "Customer support",
  "Sales performance insights",
  "Referral rewards program access",
  "Audience analytics",
  "After-sales service management",
];

export const planDetails = {
  free: {
    name: "Free",
    pricing: {
      monthly: {
        price: "FREE",
        billing: "Forever free for individuals",
        amount: 0,
      },
      yearly: {
        price: "FREE",
        billing: "Forever free for individuals",
        amount: 0,
      },
    },
    features: {
      "Auto-replies": "✓",
      "Personalized greetings": "X",
      "Queries per month": "10",
      "Storage space": "20MB",
      "Artwork recommendations": "Simple",
      "Daily fortune draw game": "✓",
      "Transaction and sales tracking": "X",
      "Fraud protection": "X",
      "Customizable chat responses": "X",
      "AI-generated buyer recommendations": "X",
      "Customer support": "Basic",
      "Sales performance insights": "X",
      "Referral rewards program access": "X",
      "Audience analytics": "X",
      "After-sales service management": "X",
    },
  },
  plus: {
    name: "Plus",
    pricing: {
      monthly: { price: "$9", billing: "$9 billed monthly", amount: 9 },
      yearly: {
        price: "$108",
        billing: "$9 per user / month billed annually",
        amount: 108,
      },
    },
    features: {
      "Auto-replies": "✓",
      "Personalized greetings": "✓",
      "Queries per month": "30",
      "Storage space": "50MB",
      "Artwork recommendations": "Personalized",
      "Daily fortune draw game": "✓",
      "Transaction and sales tracking": "✓",
      "Fraud protection": "X",
      "Customizable chat responses": "X",
      "AI-generated buyer recommendations": "✓",
      "Customer support": "Priority",
      "Sales performance insights": "Basic",
      "Referral rewards program access": "X",
      "Audience analytics": "X",
      "After-sales service management": "X",
    },
  },
  premium: {
    name: "Prem",
    pricing: {
      monthly: { price: "$16", billing: "$16 billed monthly", amount: 16 },
      yearly: {
        price: "$192",
        billing: "$16 per user / month billed annually",
        amount: 192,
      },
    },
    features: {
      "Auto-replies": "✓",
      "Personalized greetings": "✓",
      "Queries per month": "100",
      "Storage space": "200MB",
      "Artwork recommendations": "Advanced",
      "Daily fortune draw game": "✓",
      "Transaction and sales tracking": "✓",
      "Fraud protection": "✓",
      "Customizable chat responses": "X",
      "AI-generated buyer recommendations": "✓",
      "Customer support": "Priority",
      "Sales performance insights": "Basic",
      "Referral rewards program access": "✓",
      "Audience analytics": "Basic",
      "After-sales service management": "✓",
    },
  },
  pro: {
    name: "Pro",
    pricing: {
      monthly: { price: "$32", billing: "$32 billed monthly", amount: 32 },
      yearly: {
        price: "$384",
        billing: "$32 per user / month billed annually",
        amount: 384,
      },
    },
    features: {
      "Auto-replies": "✓",
      "Personalized greetings": "✓",
      "Queries per month": "Unlimited",
      "Storage space": "500MB",
      "Artwork recommendations": "Advanced",
      "Daily fortune draw game": "✓",
      "Transaction and sales tracking": "Detailed analytics",
      "Fraud protection": "Full",
      "Customizable chat responses": "✓",
      "AI-generated buyer recommendations": "✓",
      "Customer support": "VIP",
      "Sales performance insights": "Detailed",
      "Referral rewards program access": "✓",
      "Audience analytics": "Advanced",
      "After-sales service management": "✓",
    },
  },
};
